version: "3.9" 

services:
  allmende-ml:
    container_name: ml
    build: ./ml
    restart: always
    environment:
      FLASK_APP: api
    volumes:
     - ./ml/saved_model:/var/src/allmende-ml/saved_model
    ports:
      - 5000:5000
  mongo-db:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    volumes:
      - allmende:/data/db
    ports:
      - 27017:27017
  
  mongo-express:
    image: mongo-express:0.54.0 # latest image
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - allmende:/data/dbui
    depends_on:
      - mongo-db
      - allmende-server
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PW}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PW}
  redis-db:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - allmende:/data
    ports:
      - 6379:6379
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - allmende-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  allmende-server: 
    container_name: server
    build: ./server
    restart: always
    volumes:
      - allmende:/var/src/allmende-server/logs
      - allmende:/var/src/allmende-server/uploads
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PW: ${MONGO_PW}
      MONGO_HOST: ${MONGO_HOST}
      SECRET: ${SECRET}
      REDIS_HOST: ${REDIS_HOST}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      ML_URL: allmende-ml
    depends_on:
      - mongo-db
      - redis-db
      - allmende-ml
    ports:
      - 3000:3000
  allmende-client: 
    container_name: client
    depends_on:
     - allmende-server
    build: ./client
    stdin_open: true
    restart: always
  allmende-portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    ports:
      - "9000:9000"
      - 8000:8000
    environment:
      - VIRTUAL_HOST=portainer.allmendeapp.xyz
      - VIRTUAL_PORT=9000
volumes:
  allmende:
  portainer:
