version: "3.9" 
services:
  allmende-server: 
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - allmende:/var/src/allmende-server/logs
      - allmende:/var/src/allmende-serer/uploads
    environment:
      MONGO_USER: admin
      MONGO_PW: password
      MONGO_HOST: mongo-db
      SECRET: allmende_super_secret
      NODE_ENV: production
      REDIS_HOST: redis-db
    depends_on:
      - mongo-db
      - redis-db
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  redis-db:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - allmende:/data
volumes:
  allmende:
