version: "3.9" 
services:
  # allmende-server: 
  #   build: ./server
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - /Users/all/logs:/var/src/allmende-server/logs
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    