version: "3.9" 

services:
  allmende-ml:
    build: ./ml
    restart: always
    environment:
      FLASK_APP: api
    volumes:
     - ./ml/saved_model:/var/src/allmende-ml/saved_model
    ports:
      - 5000:5000
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    volumes:
      - allmende:/data/db
    ports:
      - 27017:27017
  redis-db:
    image: redis
    restart: always
    volumes:
      - allmende:/data
    ports:
      - 6379:6379
  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - allmende-server
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  allmende-server: 
    build: ./server
    restart: always
    volumes:
      - allmende:/var/src/allmende-server/logs
      - allmende:/var/src/allmende-server/uploads
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PW: ${MONGO_PW}
      MONGO_HOST: ${MONGO_HOST}
      SECRET: ${SECRET}
      REDIS_HOST: ${REDIS_HOST}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      ML_URL: allmende-ml
    depends_on:
      - mongo-db
      - redis-db
      - allmende-ml
    ports:
      - 3000:3000
  allmende-client: 
    depends_on:
     - allmende-server
    build: ./client
    stdin_open: true
    restart: always
  allmende-portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    ports:
      - "9000:9000"
      - 8000:8000
    environment:
      - VIRTUAL_HOST=portainer.allmendeapp.xyz
      - VIRTUAL_PORT=9000
volumes:
  allmende:
  portainer:
