version: "3.9" 
services:
  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - allmende:/data/db
  redis-db:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - allmende:/data
volumes:
  allmende:
