name: Client Linting

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Run linters for client
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          git_name: Linter Action
          git_email: norepy@allmende
          check_name: Client-${linter}
          commit_message: ':rotating_light: Fix code style issues with ${linter} for client'
          eslint: true
          eslint_dir: client/
          eslint_extensions: vue,js,jsx,cjs,mjs,ts,tsx,cts,mts
          prettier: true
          prettier_dir: client/
