name: Server Linting

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'
  pull_request:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Run linters for server
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          git_name: Linter Action
          git_email: norepy@allmende
          check_name: Server-${linter}
          commit_message: 'Linter Fix code style issues with ${linter} for server'
          eslint: true
          eslint_dir: server/
          eslint_extensions: js,ts
          prettier: true
          prettier_dir: server/
